### ISSUE TITLE
Do you know QuickIO.NET & AlphaFS ?

### ISSUE THREAD

**Issue by carkrueger** [peteraritchie/EffectiveIoC#1]
Hi,

do you know QuickIO.NET & AlphaFS?
Both are libs with long path support.
At least QuickIO.NET is also meant as a drop in replacement

Maybe join the effort

greetings
Carsten

**Comment by peteraritchie** [comment]
yes, both have some level of long path support; but also add a lot of other functionality that some teams don't need/want.
